import type { Metadata } from "next";
import { Geist, Geist_Mono, Fredoka , Poppins, Inter} from "next/font/google";
import "./globals.css";
import { IChildren } from "@/interface";
import { FC } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cook-shop",
  description: "Generated by Nayem Shanto",
};

const RootLayout: FC<IChildren> = ({ children }) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} ${fredoka.variable} ${poppins.variable} ${inter.variable}  ntialiased`}>
      {children}
    </body>
  </html>
);
export default RootLayout;
